language: python

matrix:
  include:
    - os: linux
      env:
        - LUA="lua=5.1"
    - os: linux
      env:
        - LUA="lua=5.2"
    - os: linux
      env:
        - LUA="luajit=2.0"
    - os: linux
      env:
        - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov

install:
  - luarocks make

script:
  - luacheck src spec
  - busted -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
